### ISSUE TITLE
Error: "no writecb in Transform class"

### ISSUE THREAD

**Issue by issander** [gulp-community/gulp-less#111]
The error "no writecb in Transform class" is being thrown seemingly at random by the following task:

```
gulp.task('debug', function () {
    gulp.src('www/beheer/_lib/css/style.less')
        .pipe(plumber(function(error){
            gutil.log(gutil.colors.red(error.message));
            gutil.beep();
        }))
        .pipe(less())
        .pipe(gulp.dest('www/_lib/dist'));
});
```

After some searching I found the following issue that suggested that this particular error is caused by calling the callback function multiple times: https://github.com/geopipes/elasticsearch-backend/issues/1

After placing some console.log lines in the gulp-less code it seems that the following part is to blame:

```
cb(null, file);
```

(index.js - line 68 - version 1.3.7)

In my case this callback is being called three times, the later two producing the error.

**Comment by jbcpollak** [comment]
We seem to be getting this same error with v3.0.1, is that possible?

**Comment by contra** [comment]
@jbcpollak Wipe node modules and reinstall maybe?

**Comment by jbcpollak** [comment]
I guess we are seeing a separate bug with similar symptoms. It seems to be caused by the use of the CSS3 /deep/ feature. 

It looks like gulp-less depends on less ^2.1.1 and support for /deep/ was added in less 2.4.0.

https://github.com/less/less.js/issues/2023

When we removed /deep/, the problem went away. Any chance an updated gulp-less could be released to depend on the newest less?

**Comment by contra** [comment]
@jbcpollak done

**Comment by contra** [comment]
Also you can just npm update, we use the range ^2.1.0 which includes 2.4.0

**Comment by jiaweihli** [comment]
Seeing this issue with `gulp-autoprefixer` on 3.0.2.

**Comment by contra** [comment]
@jiaweihli So open it on gulp-autoprefixer :palm_tree:

**Comment by wrightling** [comment]
I get this same error with gulp-less 3.0.3, but not if I go back to 3.0.2. I'm not super familiar with the npm module open source world - what can I provide that is useful in terms of information?

```
2.0.0-p247 in customer_commerce/ on develop-ever
› npm list gulp-less
npm WARN unmet dependency /Users/wwright/Dev/web/frontend/customer_commerce/node_modules/gulp-eslint requires eslint@'^0.18.0' but will load
npm WARN unmet dependency /Users/wwright/Dev/web/frontend/customer_commerce/node_modules/eslint,
npm WARN unmet dependency which is version 0.19.0
customer-commerce@0.0.1 /Users/wwright/Dev/web/frontend/customer_commerce
└── gulp-less@3.0.3


2.0.0-p247 in customer_commerce/ on develop-ever
› gulp less
[12:38:24] Using gulpfile ~/Dev/web/frontend/customer_commerce/gulpfile.js
[12:38:24] Starting 'less'...
[12:38:27] [less] [Error: no writecb in Transform class]
```

**Comment by contra** [comment]
This is a weird thing that pops up sometimes where npm fails to install a dependency correctly (I think readable-stream). `rm -rf node_modules && npm install` to make things work correctly when npm shits the bed.

**Comment by CocaCola183** [comment]
I got the same problem, and I fiexed by doing this:
```
.pipe(less({
      paths: [ path.join(__dirname, 'less', 'includes') ]
    }))
```

**Comment by AnatolyRugalev** [comment]
I had this issue when used old version of nodejs (0.10). Resolved with upgrading it to 0.12

**Comment by mark-williams** [comment]
Upgrading node did the trick for me too.

**Comment by sbhaktha** [comment]
I am seeing this issue! Using

```
    "gulp": "3.9.1",
    "gulp-less": "3.0.5",
```

Any ideas? Thanks!

**Comment by developerbmw** [comment]
Same here @sbhaktha

**Comment by developerbmw** [comment]
Ok updating nodejs fixed it

**Comment by vlaim** [comment]
I got this problem after updating to gulp 4 🤔

**Comment by wmai** [comment]
> I got this problem after updating to gulp 4
> _- vlaim_

Me too.
