### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by roopkt** [gulp-community/gulp-less#295]
Hi
I am using "gulp-less": "^3.5.0" and I am not able to import variables getting below error:

[15:33:02] Plumber found unhandled error:
 Error in plugin "gulp-less"
Message:
    variable @import is undefined in file...\Content\assets\less\myfiles.less line no. 3
Details:
    type: Name
    filename: ...\Content\assets\less\myfiles.less
    index: 53
    line: 3
    callLine: NaN
    callExtract: undefined
    column: 0    extract: /*COLORS*/,@import "variables.less"; ,
    lineNumber: 3
    fileName: ..\Content\assets\less\myfile.less
variable.less file is below

@dark-gray: #000;
@light-gray: #a4aeb3;
@teal: #043a4e;
@orange: #d74c15;
@hover-orange: #b44012;
myfile.less is below

/*COLORS*/
@import "variables.less"; 

@primaryTextColor: @dark-gray;
@secondaryTextColor: @light-gray;
@primaryAccentColor: @teal;
@secondaryAccentColor: @orange;

**Comment by stevelacy** [comment]
This is an error with [less](https://github.com/less/less.js/) not this project.
