### ISSUE TITLE
Version mismatching

### ISSUE THREAD

**Issue by mriot** [gulp-community/gulp-less#315]
Ahoi,
there are some weird version mismatches within this project.
In every corner there's another version number:

- on NPM: 5.0.0 (which seems to be correct) -> <https://www.npmjs.com/package/gulp-less>
- on GitHub
  - Latest release: 4.0.0 (23 Feb 2018 and no Tags)
  - Project description: A LESS plugin for Gulp - latest is **3.5.0 on npm**
  - Changelog: 3.2.0

It's getting confusing. :)

**Comment by neokio** [comment]
I agree, this is rather confusing. Running an `ncu` revealed the new npm `gulp-less` major release, but when I went to study whether there were breaking changes, the latest major release on github was 3 years ago, and there was no change-log or upgrade notes. Confusing.

**Comment by contra** [comment]
I agree it is confusing - I'm going to switch off of the changelog.md and use releases.
