### ISSUE TITLE
problem with compiling

### ISSUE THREAD

**Issue by WuglyakBolgoink** [gulp-community/gulp-less#316]
Hallo guys,

maybe anyone can help me.

after migration to the latest version of `gulp-less` plugin our less files will be compiled wrong.

example:
I import rz-slider less file whock contain some classes like

```css
width: 32px /2;
```

after build before upgrading the result file contain correct `width: 16px`, but now the result file contain original values: `width: 32px /2;`

Am I missed something?

**Comment by papegaaij** [comment]
We are seeing the exact same issues. All divisions are broken. Addition, subtraction and multiplication work fine, but divisions do not. For example: `70rem - 2*@spacing` results in `67rem`, but `@spacing / 2` results in `1.5rem/2`. This broke after upgrading from 4.0.1 to 5.0.0. Reverting to 4.0.1 fixed the arithmetic, so this is definitely a regression in 5.0.0.

**Comment by WuglyakBolgoink** [comment]
Hallo @papegaaij !

Actually same happened with `SASS/SCSS` too, they both changed division math operations and you need to wrap this with parentheses!!!!

Example:

```
before
> width: 32px /2;

after:
> width: (32px /2);
```

nothing more!
