### ISSUE TITLE
Update Less dependency to 4.2.0

### ISSUE THREAD

**Issue by Brugman** [gulp-community/gulp-less#323]
4.2.0 released in September, and supports (amongst other things) the nested container query syntax.

I edited the version of less in the gulp-less package.json and ran an `npm i`... and it seemed to work.

If it is as easy as a version bump, could someone please push that change?

**Comment by vishalpareekelisa** [comment]
It's been long since this feature was asked but looks like gulp-less is no longer updating the change, is there any fork available with this change?

**Comment by yocontra** [comment]
Not sure what the issue is here - https://github.com/gulp-community/gulp-less/blob/master/package.json#L24

If you look at the version range specified here, it will install anything matching ^4.0.0 (which includes 4.2.0). Run npm upgrade?

**Comment by Brugman** [comment]
I don't remember what I saw in December, but the replies made me give this "bug" another shot.

This package wasn't the cause! My use of `gulp-clean-css` was removing the container query code. That package isn't getting updates, so I replaced it with `@sequencemedia/gulp-clean-css`, and that fixed it.

Sorry to bother you.
